### ISSUE TITLE
package io.crossroad.rncardano does not exist

### ISSUE THREAD

**Issue by hungdopamineapp** [Emurgo/react-native-cardano#16]
I tried to integrate cardano into my project and got this issue. I also try do something in this [pull request](https://github.com/Emurgo/react-native-cardano/pull/14) but it still not work. Can you help to solve this issue? Many thanks

My system:
- macOs Big Sur (11.6.1)
-  "react-native": "0.64.2"

Issue:
`/Users/admin/cma_smooth/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:55: error: package io.crossroad.rncardano does not exist
import io.crossroad.rncardano.CardanoPackage;
                             ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

    at makeError (/Users/admin/cma_smooth/node_modules/execa/index.js:174:9)
    at /Users/admin/cma_smooth/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/admin/cma_smooth/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/admin/cma_smooth/node_modules/@react-native-community/cli/build/index.js:186:9)`

**Comment by v-almonacid** [comment]
This package has been deprecated in favor of https://github.com/Emurgo/react-native-haskell-shelley

So I would suggest to use that one instead, as all the functionalities and cryptographic primitives that are relevant in the current Cardano network are there now.

**Comment by PiotrNap** [comment]
Hey @v-almonacid ,just a suggestion, maybe this repository should be tagged as deprecated? Thanks for all you're doing anyway!

**Comment by v-almonacid** [comment]
> Hey @v-almonacid ,just a suggestion, maybe this repository should be tagged as deprecated? Thanks for all you're doing anyway!

Hey! I no longer work for Emurgo so I don't have the privileges to do this, and looks like I cannot tag any current Emurgo devs here 😕

**Comment by PiotrNap** [comment]
Oh, okay. Thanks for your response.
