### ISSUE TITLE
Some problems with using libraries in RN

### ISSUE THREAD

**Issue by BenLakes** [Emurgo/react-native-cardano#2]
1.npm returns 404 error
2.Android Studio  3 
![2018-11-06 7 37 30](https://user-images.githubusercontent.com/15206046/48106616-1b314700-e277-11e8-862b-75af2e5b604e.png)
3.iOS 
![2018-11-07 11 28 46](https://user-images.githubusercontent.com/15206046/48108956-7fa4d400-e280-11e8-8020-73688579a758.png)

4. Whether the loadRustModule() needs to initialize the Rust

Is there any missing step？

**Comment by ypopovych** [comment]
1. It's not in the NPM registry yet. Install from git for now.
2. Change minSdkVersion for android application from 16 to 21 (in gradle file). The library depends on Rust code, and native format changed from SDK 21.
3. Seems as you are sending wrong data to API call (or this is a bug)
4. No. It loads Rust automatically.
