### ISSUE TITLE
Questions about using certain methods

### ISSUE THREAD

**Issue by BenLakes** [Emurgo/react-native-cardano#3]
Using the modules' HdWallet. FromEnhancedEntropy () 'reference' project - icarus - chrome project transfer way, capture some of the problems, can I change how to modify. There are no examples or documentation (I'm not familiar with the use of this, mostly using some of the methods under the screenshots). Thank you very much!

![2018-11-14 9 53 42](https://user-images.githubusercontent.com/15206046/48454680-3e1da700-e7f3-11e8-8691-d6dc1ae1d973.png)
![wechate0efaceb2615e5bf29b91770c7b93446](https://user-images.githubusercontent.com/15206046/48454683-41b12e00-e7f3-11e8-8f0d-783cbafdc477.png)
![wechatf788caedfd74a8f9e5d8884bd412f080](https://user-images.githubusercontent.com/15206046/48454685-44138800-e7f3-11e8-9792-456a73a64eaa.png)
![2018-11-14 9 42 51](https://user-images.githubusercontent.com/15206046/48454764-8f2d9b00-e7f3-11e8-9a6a-c12771f48c63.png)

Direct transmission of hexadecimal reporting for native errors：
![2018-11-14 10 29 06](https://user-images.githubusercontent.com/15206046/48455972-37ddf980-e7f8-11e8-8ac1-e9de1898d6f5.png)

**Comment by ypopovych** [comment]
Both fields should be hex strings (password too). Check index.d.ts file for proper types.

**Comment by BenLakes** [comment]
May I ask you again if the hex string is to be treated with the "bip39.mnemonictoentropy ()" function. You can still use buffer.from (password, 'base64').tostring ('hex'). Otherwise the password does not appear to comply with the "bip39.mnemonictoentropy ()" processing rule

**Comment by BenLakes** [comment]
All my errors seem to have been caused by the new version. It's ok to revert back to the old version.
