### ISSUE TITLE
Publish the Android library on jcenter

### ISSUE THREAD

**Issue by droidjavier** [Emurgo/react-native-cardano#4]
Hi!

This is not an issue itself but more as a improvement proposal.

It would be nice to have the Android library in jcenter or another software distribution service so that the developer doesn't need to download/update the library manually by cloning the repo.

**Comment by ypopovych** [comment]
React native uses NPM for library distribution. Library will be pushed into NPM

**Comment by droidjavier** [comment]
Alright, so you would sync with npm and create the link with your project and react-native-cardano with gradle? Thanks

**Comment by ypopovych** [comment]
Yep. It works this way from RN 0.47. You should install it via NPM, and then link with it (You can use `react-native link` to link it with RN app.

**Comment by droidjavier** [comment]
Cool! Thanks for the explanation @ypopovych !
