### ISSUE TITLE
npm install react-native-cardano --save Issue*

### ISSUE THREAD

**Issue by walter-grace** [Emurgo/react-native-cardano#5]
When I type npm install react-native-cardano --save: the following error occurs.

_npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-cardano - Not found
npm ERR! 404 
npm ERR! 404  'react-native-cardano@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:_
Any solutions?

**Comment by SebastienGllmt** [comment]
We don't have an package for this library unfortunately. For Yoroi-Mobile we just specify the Git repo directly: https://github.com/Emurgo/yoroi-mobile/blob/develop/package.json#L57

**Comment by v-almonacid** [comment]
Indeed, the instructions are misleading so I updated them https://github.com/Emurgo/react-native-cardano/pull/8
